// Card decks. `both: true` means both players answer the card together.
// `adult: true` decks stay hidden until turned on in Settings.
window.DECKS = [
  {
    id: "warm", name: "Warm up", blurb: "Easy questions to get talking", cards: [
      "What's the best thing that happened to you this week?",
      "What song have you had stuck in your head lately?",
      "If we had a free day tomorrow with no plans, how would you spend it?",
      "What's a small thing that instantly puts you in a good mood?",
      "What food could you happily eat every day for a month?",
      "What's something you're looking forward to right now?",
      "Which fictional world would you live in for a year?",
      "What's the most useless talent you have?",
      "What's a habit of mine you secretly find adorable?",
      "If you could master one skill overnight, what would it be?",
      "What's your go-to comfort movie or show, and why that one?",
      "What did you want to be when you were seven?",
      "What's the best meal we've ever had together?",
      "If our life were a sitcom, what would it be called?",
      "What's one thing on your mind today that I don't know about?",
      "What's the last thing that made you laugh out loud?",
      "Which celebrity would you want as a neighbour?",
      "What's a smell that takes you straight back to childhood?",
      "What's your most-used emoji, and what does it say about you?",
      "What would your walk-up song be?",
      "What's the weirdest food combination you secretly love?",
      "If you opened a small shop, what would it sell?",
      "What app on your phone could you not live without?",
      "What's a word you love the sound of?",
      "What's the best gift you've ever received?"
    ]
  },
  {
    id: "story", name: "Our story", blurb: "Memories from your time together", cards: [
      "What was your very first impression of me?",
      "When did you first know you loved me?",
      "What's a moment with me you replay in your head?",
      "What's the funniest thing that's happened to us?",
      "Which trip or day out of ours would you relive tomorrow?",
      "What's something I did early on that won you over?",
      "When have you felt most proud of us as a team?",
      "What's a tiny everyday moment with me that you treasure?",
      "What's a hard time we got through that made us stronger?",
      "What's an inside joke of ours you never get tired of?",
      "When did you know you wanted to marry me?",
      "What do you remember about our wedding day that I might have missed?",
      "What's one photo of us that sums us up perfectly?",
      "How have I changed since we met?",
      "What would you brag about to a stranger about our relationship?",
      "What do you remember about our first date?",
      "What's the best surprise I've ever given you?",
      "What's a fight we had that's funny now?",
      "Which of our homes holds your favourite memories?",
      "What did your friends or family say about me when they first met me?",
      "What's a song that will always remind you of us?",
      "What's the most spontaneous thing we've done together?",
      "What's something I taught you without realising it?",
      "Which holiday or celebration with me stands out the most?",
      "What's a moment you were surprised by how well I knew you?"
    ]
  },
  {
    id: "dreams", name: "Dreams", blurb: "The future you're building", cards: [
      "Where should we go next, and what's the first thing we do when we land?",
      "Describe an ordinary Tuesday for us ten years from now.",
      "What's one adventure you want us to have before we're old and grey?",
      "If money weren't an issue, what would you do with your days?",
      "What tradition would you love for us to start?",
      "What skill would you love us to learn together?",
      "Describe one room in our dream home in detail.",
      "What's something you want to accomplish this year?",
      "If we could live anywhere for one year, where would it be?",
      "What's a dream you've put aside that you'd like to revisit?",
      "What do you want our life to feel like when we're 80?",
      "What would our ideal anniversary look like this year?",
      "What's one thing you want more of in our life together?",
      "If we wrote a bucket list tonight, what are your top three?",
      "What kind of legacy do you want to leave?",
      "What's a small luxury you'd like us to treat ourselves to more often?",
      "If we started a side project together, what would it be?",
      "What's a place from your childhood you want to show me?",
      "What would our perfect weekend away look like, hour by hour?",
      "What do you hope people say about us as a couple?",
      "What's something you want us to save up for?",
      "What would you want our home to feel like when guests walk in?",
      "What's one thing you'd like to stop worrying about this year?",
      "Which friendship of ours would you like to invest more in?",
      "If we could take a sabbatical for six months, how would we spend it?"
    ]
  },
  {
    id: "deep", name: "Deep", blurb: "Slower, more honest questions", cards: [
      "When do you feel most loved by me?",
      "What's something you've rarely shared with anyone?",
      "What's a fear you've grown out of, and one you still have?",
      "What do you need more of from me when you're stressed?",
      "What did your parents do that you want us to do differently?",
      "Which moment in your life shaped you the most?",
      "What are you still learning to forgive yourself for?",
      "What does home mean to you?",
      "What's a question you wish I'd ask you more often?",
      "When did you last cry, and what was it about?",
      "What part of yourself do you hope I always see?",
      "What's a belief you held strongly that has changed?",
      "What makes you feel truly understood?",
      "What's one way I could love you better this month?",
      "What are you most grateful for right now, and why?",
      "What's something you find hard to ask for?",
      "When do you feel most like yourself?",
      "What's a compliment that stuck with you for years?",
      "What does a good apology look like to you?",
      "What's one thing about your past you wish I'd been there for?",
      "What's something you're proud of that you rarely talk about?",
      "How do you know when you need time alone?",
      "What's a lesson you learned the hard way?",
      "What does a perfect day of rest look like for you?",
      "What do you think we're both still learning about each other?"
    ]
  },
  {
    id: "care", name: "Appreciation", blurb: "Say the kind things out loud", cards: [
      "Tell me three things I did this week that you appreciated.",
      "What's something I do that makes your day easier?",
      "What's a quality of mine you'd like to have yourself?",
      "When did I last make you feel proud?",
      "What's a way I show love that you didn't notice at first?",
      "Finish the sentence: I feel safe with you because...",
      "What's a sacrifice I made that you never thanked me for? Thank me now.",
      "What's something I'm better at than I give myself credit for?",
      "What do you love about the way I treat other people?",
      "Which of my quirks would you miss the most?",
      "What's the kindest thing I've ever done for you?",
      "Finish the sentence: My life is better since you because...",
      "What do I do that makes you laugh every time?",
      "What's something I said that you still think about?",
      "Describe me the way you'd describe me to your best friend.",
      "What's a small gesture from me that means a lot?",
      "What do you admire about how I handle hard days?",
      "Name something I've grown in over the last year.",
      "What do you love about our home because of me?",
      "Write me a one-line love note, out loud, right now."
    ]
  },
  {
    id: "wyr", name: "Would you rather", blurb: "Both answer on three", both: true, cards: [
      "Would you rather have a beach holiday or a mountain cabin?",
      "Would you rather get breakfast in bed or dinner out?",
      "Would you rather take a road trip or a long flight somewhere far?",
      "Would you rather throw a big anniversary party or have a quiet weekend away?",
      "Would you rather go dancing at home or dancing out?",
      "Would you rather get love letters or surprise gifts?",
      "Would you rather stay in with a movie or go out for an adventure tonight?",
      "Would you rather relive our first date or skip ahead to see us in 20 years?",
      "Would you rather have a house full of pets or a house full of plants?",
      "Would you rather cook together or have a chef cook for us?",
      "Would you rather live in a tiny cottage by the sea or a loft in the city?",
      "Would you rather be able to read my mind for a day or have me read yours?",
      "Would you rather go stargazing or watch the sunrise?",
      "Would you rather have a weekly date night or a monthly weekend away?",
      "Would you rather explore a new city or go back to a favourite place?",
      "Would you rather slow dance in the kitchen or karaoke duet in public?",
      "Would you rather win a dream holiday or a year of free takeaway?",
      "Would you rather have a picnic in the park or dinner on a rooftop?",
      "Would you rather we learn to sail or learn to salsa?",
      "Would you rather write our love story as a novel or a song?"
    ]
  },
  {
    id: "likely", name: "Who's more likely", blurb: "Point at each other on three", both: true, cards: [
      "Who's more likely to cry at a movie?",
      "Who said 'I love you' first?",
      "Who's the bigger romantic?",
      "Who would survive longer in the wild?",
      "Who apologises first after an argument?",
      "Who's more likely to get us lost?",
      "Who's the better cook?",
      "Who's more likely to forget an anniversary?",
      "Who steals the blanket?",
      "Who's more likely to start a conversation with a stranger?",
      "Who's more likely to plan a surprise?",
      "Who's the bigger night owl?",
      "Who's more likely to sing in the shower?",
      "Who would win a game show?",
      "Who's more likely to adopt a pet without asking?",
      "Who's the messier one?",
      "Who's more likely to fall asleep during a movie?",
      "Who takes longer to get ready?",
      "Who's more likely to eat the last snack?",
      "Who would be the better parent to a dragon?"
    ]
  },
  {
    id: "flirty", name: "Flirty", blurb: "Playful and a little cheeky", cards: [
      "What's the first thing you noticed about me physically?",
      "Which outfit of mine do you like most?",
      "Describe your ideal date night with me, start to finish.",
      "When do you find me most attractive?",
      "What's a compliment you've wanted to give me but haven't yet?",
      "What's one thing I do that drives you wild, in a good way?",
      "Recreate our first kiss. Who leans in first?",
      "Give me a 10-second compliment without stopping.",
      "What's a romantic gesture you've always secretly wanted?",
      "Whisper something you love about me.",
      "How do you like me to greet you after a long day?",
      "Describe me in three words. They all have to be flattering.",
      "What song makes you think of us in a romantic way?",
      "Hold eye contact for 30 seconds. Whoever laughs first draws the next card.",
      "What's the most attractive thing I do without realising it?",
      "Where would you take me for the perfect kiss?",
      "What's your favourite feature of mine, and why?",
      "What did you think the first time we held hands?",
      "Tell me about a time I looked so good you got distracted.",
      "What pet name do you secretly want me to call you?"
    ]
  },
  {
    id: "dares", name: "Dares", blurb: "Small romantic challenges", cards: [
      "Slow dance with me to the next song that plays.",
      "Give me a 60-second shoulder rub.",
      "Serenade me with one line of a love song.",
      "Plan our next date in under a minute, out loud.",
      "Kiss me like it's our first kiss.",
      "Draw a portrait of me in 30 seconds. No peeking.",
      "Send me a romantic text right now, even though I'm sitting here.",
      "Hold my hand for the next three cards.",
      "Do your best impression of me when I'm hungry.",
      "Tell me a story about how we'd meet if we met all over again.",
      "Give me a compliment in a different accent.",
      "Recreate a photo of us, right now.",
      "Write three things you love about me on a piece of paper and hide it for me to find later.",
      "Make me laugh in 20 seconds. Go.",
      "Teach me something you know in 60 seconds.",
      "Give me a forehead kiss and say something sweet.",
      "Pick a song for us to dance to in the kitchen this week.",
      "Share a photo from your phone that makes you think of me.",
      "Propose to me again, in the most dramatic way you can.",
      "Feed me a snack like we're in a romantic movie."
    ]
  },
  {
    id: "afterdark", name: "After dark", blurb: "For later in the evening", adult: true, cards: [
      "What's a fantasy date you've never told me about?",
      "Where's the most unexpected place you've wanted to kiss me?",
      "What's something I wear that you can't stop looking at?",
      "What's your favourite memory of us being alone together?",
      "Describe the perfect end to tonight.",
      "What's one thing you'd like us to try together?",
      "Where do you love being touched the most?",
      "What's the most attractive thing I've ever said to you?",
      "Kiss me somewhere you've never kissed me before.",
      "What's a moment you wanted me but couldn't say so?",
      "What was going through your head the first time we were intimate?",
      "Whisper what you'd like to do after this game.",
      "What's something about me that makes you weak at the knees?",
      "Give me a kiss that lasts ten seconds.",
      "What's a love scene from a film you'd want to recreate?",
      "What's your favourite way for me to show I want you?",
      "Tell me something you'd never text me.",
      "Pick the next card for me, and you choose: question or dare."
    ]
  }
];
